### PR TITLE
Improve SVG encoding

### PR DESCRIPTION
**Pull request by felthy**
Update svg encoding with latest recommendations from https://css-tricks.com/probably-dont-base64-svg/; fix newlines breaking encoding. Fixes issues described in #3.

### CODE REVIEW

**Comment by asbjornenge** [comment]
@felthy Great work 🎉 🚀  I haven't used this project in ages, so I'll just add you as a contributer and you can merge the PR yourself 👍  Do you have a npm username? I can add you there as well so you can make an updated release 👌

**Comment by 0b5vr** [comment]
I'm currently doing `npm i -D felthy/imgurify` in order to make my stuff work >_>
Couldn't you pull it?

**Comment by asbjornenge** [comment]
@FMS-Cat it's out @ 2.0.1 🎉  https://www.npmjs.com/package/imgurify

**Comment by 0b5vr** [comment]
oke thanks :pray:

**Pull request merged**
